version: '3'

# configure ingestion-edge for ci
services:
  test:
    build: .
    image: &image "${DOCKERHUB_REPO-ingestion-edge}:${CIRCLE_TAG-latest}"
    environment:
    - &route_table >-
      ROUTE_TABLE=[
        [
          "/stub/<suffix:path>",
          "projects/test/topics/stub_installer",
          ["GET"]
        ],
        [
          "/submit/telemetry/<suffix:path>",
          "projects/test/topics/telemetry"
        ],
        [
          "/submit/sslreports",
          "projects/test/topics/tls_error_reports",
          ["post", "put"]
        ],
        [
          "/submit/<suffix:path>",
          "projects/test/topics/ingestion",
          ["PoSt", "pUt"]
        ],
        [
          "/submit",
          "projects/test/topics/ingestion"
        ]
      ]
    entrypoint: pytest
    command:
    - --black
    - --flake8
    - --docstyle
    - --mypy
    - --mypy-ignore-missing-imports
    - --cov=./ingestion_edge/
